export const ERR_NOT_FOUND_EVENTS = 'ERR_NOT_FOUND_EVENTS';
export const ERR_NOT_FOUND_EVENT = 'ERR_NOT_FOUND_EVENT';
export const ERR_NOT_FOUND_BROWSER_SERVICE = 'ERR_NOT_FOUND_BROWSER_SERVICE';
export const ERR_EMAIL_NOT_FOUND = 'ERR_EMAIL_NOT_FOUND';
export const ERR_EMAIL_ALREADY_EXIST = 'ERR_EMAIL_ALREADY_EXIST';
export const ERR_NOT_FOUND_USER = 'ERR_NOT_FOUND_USER';
export const ERR_EXPIRED_CODE = 'ERR_EXPIRED_CODE';
export const ERR_10_MAX_ATTACHMENT_IN_EVENT_CODE =
  'ERR_10_MAX_ATTACHMENT_IN_EVENT_CODE';
export const EMAIL_OR_PASSWORD_IS_INCORRECT = 'EMAIL_OR_PASSWORD_IS_INCORRECT';
export const ERR_SEND_MAIL = 'ERR_SEND_MAIL';
export const ERR_ONLY_ADMIN = 'ERR_ONLY_ADMIN';
export const ERR_UPLOAD_FAILED = 'ERR_UPLOAD_FAILED';
